# Generated by Django 5.2.17 on 2026-09-14 19:35

import uuid
from django.db import migrations, models
from pathlib import Path
from django.apps.registry import Apps, apps as global_apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
import django.db.models.deletion

from authentik.lib.config import CONFIG

BUILTIN_TEMPLATES = [
    # (managed, app label, filename under <app>/templates/email/)
    (
        "goauthentik.io/email/base",
        "authentik_stages_email",
        "base.html",
    ),
    (
        "goauthentik.io/email/password-reset",
        "authentik_stages_email",
        "password_reset.html",
    ),
    (
        "goauthentik.io/email/account-confirmation",
        "authentik_stages_email",
        "account_confirmation.html",
    ),
    (
        "goauthentik.io/email/email-otp",
        "authentik_stages_authenticator_email",
        "email_otp.html",
    ),
    (
        "goauthentik.io/email/event-notification",
        "authentik_stages_email",
        "event_notification.html",
    ),
    ("goauthentik.io/email/invitation", "authentik_stages_email", "invitation.html"),
    ("goauthentik.io/email/setup", "authentik_stages_email", "setup.html"),
]


def seed_builtin_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    for managed_id, app_label, filename in BUILTIN_TEMPLATES:
        template_path = (
            Path(global_apps.get_app_config(app_label).path) / "templates" / "email" / filename
        )
        body = template_path.read_text(encoding="utf-8")
        EmailTemplate.objects.using(db_alias).update_or_create(
            managed=managed_id,
            defaults={"path": f"email/{filename}", "body": body},
        )


def remove_builtin_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(
        managed__in=[m for m, *_ in BUILTIN_TEMPLATES]
    ).delete()


def import_custom_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    template_dir = Path(CONFIG.get("email.template_dir"))
    if not template_dir.is_dir():
        return
    for file in sorted(template_dir.rglob("*.html")):
        try:
            body = file.read_text(encoding="utf-8")
        except OSError:
            continue
        EmailTemplate.objects.using(db_alias).get_or_create(
            path=file.relative_to(template_dir).as_posix(),
            managed=None,
            defaults={"body": body},
        )


def resolve_template(EmailTemplate, db_alias: str, path: str):
    templates = EmailTemplate.objects.using(db_alias).filter(path=path)
    return (
        templates.filter(managed__isnull=True).first()
        or templates.filter(managed__isnull=False).first()
    )


def backfill_emailstage_template(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailStage = apps.get_model("authentik_stages_email", "EmailStage")
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    for stage in EmailStage.objects.using(db_alias).all():
        if not stage.template_legacy:
            continue
        stage.template = resolve_template(EmailTemplate, db_alias, stage.template_legacy)
        stage.save(using=db_alias, update_fields=["template"])


def backfill_emailstage_template_reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailStage = apps.get_model("authentik_stages_email", "EmailStage")
    db_alias = schema_editor.connection.alias
    for stage in EmailStage.objects.using(db_alias).select_related("template").all():
        stage.template_legacy = stage.template.path if stage.template_id else ""
        stage.save(using=db_alias, update_fields=["template_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_email", "0006_emailstage_recovery_cache_timeout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "managed",
                    models.TextField(
                        default=None,
                        help_text="Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.",
                        null=True,
                        unique=True,
                        verbose_name="Managed by authentik",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        help_text="Path used to reference this template, similar to file paths on disk.",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ("path",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("managed__isnull", True)),
                        fields=("path",),
                        name="unique_custom_email_template_path",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("managed__isnull", False)),
                        fields=("path",),
                        name="unique_managed_email_template_path",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_builtin_templates, remove_builtin_templates),
        migrations.RunPython(import_custom_templates, migrations.RunPython.noop),
        # migrate existing templates
        migrations.RenameField(
            model_name="emailstage",
            old_name="template",
            new_name="template_legacy",
        ),
        migrations.AddField(
            model_name="emailstage",
            name="template",
            field=models.ForeignKey(
                to="authentik_stages_email.emailtemplate",
                blank=True,
                null=True,
                default=None,
                help_text="Email template to use",
                on_delete=django.db.models.deletion.PROTECT,
            ),
        ),
        migrations.RunPython(backfill_emailstage_template, backfill_emailstage_template_reverse),
        migrations.RemoveField(
            model_name="emailstage",
            name="template_legacy",
        ),
    ]
