# Generated by Django 5.2.17 on 2026-09-14 19:35

import uuid
from django.db import migrations, models
from pathlib import Path
from django.apps.registry import Apps, apps as global_apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# regression: these display names are no longer translated since they come from DB
BUILTIN_TEMPLATES = [
    # (managed, name, app label, filename under <app>/templates/email/)
    (
        "goauthentik.io/email/password-reset",
        "Password Reset",
        "authentik_stages_email",
        "password_reset.html",
    ),
    (
        "goauthentik.io/email/account-confirmation",
        "Account Confirmation",
        "authentik_stages_email",
        "account_confirmation.html",
    ),
    (
        "goauthentik.io/email/email-otp",
        "Email OTP",
        "authentik_stages_authenticator_email",
        "email_otp.html",
    ),
    (
        "goauthentik.io/email/event-notification",
        "Event Notification",
        "authentik_stages_email",
        "event_notification.html",
    ),
    ("goauthentik.io/email/invitation", "Invitation", "authentik_stages_email", "invitation.html"),
    ("goauthentik.io/email/setup", "Test Email", "authentik_stages_email", "setup.html"),
]


def seed_builtin_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    for managed_id, name, app_label, filename in BUILTIN_TEMPLATES:
        template_path = (
            Path(global_apps.get_app_config(app_label).path) / "templates" / "email" / filename
        )
        body = template_path.read_text(encoding="utf-8")
        EmailTemplate.objects.using(db_alias).update_or_create(
            managed=managed_id,
            defaults={"name": name, "body": body},
        )


def remove_builtin_templates(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(
        managed__in=[m for m, *_ in BUILTIN_TEMPLATES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_email", "0006_emailstage_recovery_cache_timeout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "managed",
                    models.TextField(
                        default=None,
                        help_text="Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.",
                        null=True,
                        unique=True,
                        verbose_name="Managed by authentik",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(seed_builtin_templates, remove_builtin_templates),
    ]
