/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AuthenticatorTelegramChallengeResponseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticatorTelegramChallengeResponseRequest{}

// AuthenticatorTelegramChallengeResponseRequest Telegram Challenge response, device is set by get_response_instance
type AuthenticatorTelegramChallengeResponseRequest struct {
	Component            *string `json:"component,omitempty"`
	Code                 *string `json:"code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticatorTelegramChallengeResponseRequest AuthenticatorTelegramChallengeResponseRequest

// NewAuthenticatorTelegramChallengeResponseRequest instantiates a new AuthenticatorTelegramChallengeResponseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticatorTelegramChallengeResponseRequest() *AuthenticatorTelegramChallengeResponseRequest {
	this := AuthenticatorTelegramChallengeResponseRequest{}
	var component string = "ak-stage-authenticator-telegram"
	this.Component = &component
	return &this
}

// NewAuthenticatorTelegramChallengeResponseRequestWithDefaults instantiates a new AuthenticatorTelegramChallengeResponseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticatorTelegramChallengeResponseRequestWithDefaults() *AuthenticatorTelegramChallengeResponseRequest {
	this := AuthenticatorTelegramChallengeResponseRequest{}
	var component string = "ak-stage-authenticator-telegram"
	this.Component = &component
	return &this
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallengeResponseRequest) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallengeResponseRequest) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallengeResponseRequest) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *AuthenticatorTelegramChallengeResponseRequest) SetComponent(v string) {
	o.Component = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallengeResponseRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallengeResponseRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallengeResponseRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *AuthenticatorTelegramChallengeResponseRequest) SetCode(v string) {
	o.Code = &v
}

func (o AuthenticatorTelegramChallengeResponseRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticatorTelegramChallengeResponseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticatorTelegramChallengeResponseRequest) UnmarshalJSON(data []byte) (err error) {
	varAuthenticatorTelegramChallengeResponseRequest := _AuthenticatorTelegramChallengeResponseRequest{}

	err = json.Unmarshal(data, &varAuthenticatorTelegramChallengeResponseRequest)

	if err != nil {
		return err
	}

	*o = AuthenticatorTelegramChallengeResponseRequest(varAuthenticatorTelegramChallengeResponseRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "component")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticatorTelegramChallengeResponseRequest struct {
	value *AuthenticatorTelegramChallengeResponseRequest
	isSet bool
}

func (v NullableAuthenticatorTelegramChallengeResponseRequest) Get() *AuthenticatorTelegramChallengeResponseRequest {
	return v.value
}

func (v *NullableAuthenticatorTelegramChallengeResponseRequest) Set(val *AuthenticatorTelegramChallengeResponseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticatorTelegramChallengeResponseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticatorTelegramChallengeResponseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticatorTelegramChallengeResponseRequest(val *AuthenticatorTelegramChallengeResponseRequest) *NullableAuthenticatorTelegramChallengeResponseRequest {
	return &NullableAuthenticatorTelegramChallengeResponseRequest{value: val, isSet: true}
}

func (v NullableAuthenticatorTelegramChallengeResponseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticatorTelegramChallengeResponseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
