/*
authentik

Making authentication simple.

API version: 2026.11.0-rc1
Contact: hello@goauthentik.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthenticatorTelegramChallenge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticatorTelegramChallenge{}

// AuthenticatorTelegramChallenge Telegram Setup challenge
type AuthenticatorTelegramChallenge struct {
	FlowInfo             *ContextualFlowInfo       `json:"flow_info,omitempty"`
	Component            *string                   `json:"component,omitempty"`
	ResponseErrors       *map[string][]ErrorDetail `json:"response_errors,omitempty"`
	PendingUser          string                    `json:"pending_user"`
	PendingUserAvatar    string                    `json:"pending_user_avatar"`
	CodeRequired         *bool                     `json:"code_required,omitempty"`
	BotUsername          string                    `json:"bot_username"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticatorTelegramChallenge AuthenticatorTelegramChallenge

// NewAuthenticatorTelegramChallenge instantiates a new AuthenticatorTelegramChallenge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticatorTelegramChallenge(pendingUser string, pendingUserAvatar string, botUsername string) *AuthenticatorTelegramChallenge {
	this := AuthenticatorTelegramChallenge{}
	var component string = "ak-stage-authenticator-telegram"
	this.Component = &component
	this.PendingUser = pendingUser
	this.PendingUserAvatar = pendingUserAvatar
	var codeRequired bool = false
	this.CodeRequired = &codeRequired
	this.BotUsername = botUsername
	return &this
}

// NewAuthenticatorTelegramChallengeWithDefaults instantiates a new AuthenticatorTelegramChallenge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticatorTelegramChallengeWithDefaults() *AuthenticatorTelegramChallenge {
	this := AuthenticatorTelegramChallenge{}
	var component string = "ak-stage-authenticator-telegram"
	this.Component = &component
	var codeRequired bool = false
	this.CodeRequired = &codeRequired
	return &this
}

// GetFlowInfo returns the FlowInfo field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallenge) GetFlowInfo() ContextualFlowInfo {
	if o == nil || IsNil(o.FlowInfo) {
		var ret ContextualFlowInfo
		return ret
	}
	return *o.FlowInfo
}

// GetFlowInfoOk returns a tuple with the FlowInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetFlowInfoOk() (*ContextualFlowInfo, bool) {
	if o == nil || IsNil(o.FlowInfo) {
		return nil, false
	}
	return o.FlowInfo, true
}

// HasFlowInfo returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallenge) HasFlowInfo() bool {
	if o != nil && !IsNil(o.FlowInfo) {
		return true
	}

	return false
}

// SetFlowInfo gets a reference to the given ContextualFlowInfo and assigns it to the FlowInfo field.
func (o *AuthenticatorTelegramChallenge) SetFlowInfo(v ContextualFlowInfo) {
	o.FlowInfo = &v
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallenge) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallenge) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *AuthenticatorTelegramChallenge) SetComponent(v string) {
	o.Component = &v
}

// GetResponseErrors returns the ResponseErrors field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallenge) GetResponseErrors() map[string][]ErrorDetail {
	if o == nil || IsNil(o.ResponseErrors) {
		var ret map[string][]ErrorDetail
		return ret
	}
	return *o.ResponseErrors
}

// GetResponseErrorsOk returns a tuple with the ResponseErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetResponseErrorsOk() (*map[string][]ErrorDetail, bool) {
	if o == nil || IsNil(o.ResponseErrors) {
		return nil, false
	}
	return o.ResponseErrors, true
}

// HasResponseErrors returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallenge) HasResponseErrors() bool {
	if o != nil && !IsNil(o.ResponseErrors) {
		return true
	}

	return false
}

// SetResponseErrors gets a reference to the given map[string][]ErrorDetail and assigns it to the ResponseErrors field.
func (o *AuthenticatorTelegramChallenge) SetResponseErrors(v map[string][]ErrorDetail) {
	o.ResponseErrors = &v
}

// GetPendingUser returns the PendingUser field value
func (o *AuthenticatorTelegramChallenge) GetPendingUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PendingUser
}

// GetPendingUserOk returns a tuple with the PendingUser field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetPendingUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingUser, true
}

// SetPendingUser sets field value
func (o *AuthenticatorTelegramChallenge) SetPendingUser(v string) {
	o.PendingUser = v
}

// GetPendingUserAvatar returns the PendingUserAvatar field value
func (o *AuthenticatorTelegramChallenge) GetPendingUserAvatar() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PendingUserAvatar
}

// GetPendingUserAvatarOk returns a tuple with the PendingUserAvatar field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetPendingUserAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingUserAvatar, true
}

// SetPendingUserAvatar sets field value
func (o *AuthenticatorTelegramChallenge) SetPendingUserAvatar(v string) {
	o.PendingUserAvatar = v
}

// GetCodeRequired returns the CodeRequired field value if set, zero value otherwise.
func (o *AuthenticatorTelegramChallenge) GetCodeRequired() bool {
	if o == nil || IsNil(o.CodeRequired) {
		var ret bool
		return ret
	}
	return *o.CodeRequired
}

// GetCodeRequiredOk returns a tuple with the CodeRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetCodeRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.CodeRequired) {
		return nil, false
	}
	return o.CodeRequired, true
}

// HasCodeRequired returns a boolean if a field has been set.
func (o *AuthenticatorTelegramChallenge) HasCodeRequired() bool {
	if o != nil && !IsNil(o.CodeRequired) {
		return true
	}

	return false
}

// SetCodeRequired gets a reference to the given bool and assigns it to the CodeRequired field.
func (o *AuthenticatorTelegramChallenge) SetCodeRequired(v bool) {
	o.CodeRequired = &v
}

// GetBotUsername returns the BotUsername field value
func (o *AuthenticatorTelegramChallenge) GetBotUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BotUsername
}

// GetBotUsernameOk returns a tuple with the BotUsername field value
// and a boolean to check if the value has been set.
func (o *AuthenticatorTelegramChallenge) GetBotUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BotUsername, true
}

// SetBotUsername sets field value
func (o *AuthenticatorTelegramChallenge) SetBotUsername(v string) {
	o.BotUsername = v
}

func (o AuthenticatorTelegramChallenge) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticatorTelegramChallenge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FlowInfo) {
		toSerialize["flow_info"] = o.FlowInfo
	}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.ResponseErrors) {
		toSerialize["response_errors"] = o.ResponseErrors
	}
	toSerialize["pending_user"] = o.PendingUser
	toSerialize["pending_user_avatar"] = o.PendingUserAvatar
	if !IsNil(o.CodeRequired) {
		toSerialize["code_required"] = o.CodeRequired
	}
	toSerialize["bot_username"] = o.BotUsername

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticatorTelegramChallenge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pending_user",
		"pending_user_avatar",
		"bot_username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticatorTelegramChallenge := _AuthenticatorTelegramChallenge{}

	err = json.Unmarshal(data, &varAuthenticatorTelegramChallenge)

	if err != nil {
		return err
	}

	*o = AuthenticatorTelegramChallenge(varAuthenticatorTelegramChallenge)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "flow_info")
		delete(additionalProperties, "component")
		delete(additionalProperties, "response_errors")
		delete(additionalProperties, "pending_user")
		delete(additionalProperties, "pending_user_avatar")
		delete(additionalProperties, "code_required")
		delete(additionalProperties, "bot_username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticatorTelegramChallenge struct {
	value *AuthenticatorTelegramChallenge
	isSet bool
}

func (v NullableAuthenticatorTelegramChallenge) Get() *AuthenticatorTelegramChallenge {
	return v.value
}

func (v *NullableAuthenticatorTelegramChallenge) Set(val *AuthenticatorTelegramChallenge) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticatorTelegramChallenge) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticatorTelegramChallenge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticatorTelegramChallenge(val *AuthenticatorTelegramChallenge) *NullableAuthenticatorTelegramChallenge {
	return &NullableAuthenticatorTelegramChallenge{value: val, isSet: true}
}

func (v NullableAuthenticatorTelegramChallenge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticatorTelegramChallenge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
