# Generated by Django 5.2.17 on 2026-09-14 19:35

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def resolve_template(EmailTemplate, db_alias: str, path: str):
    templates = EmailTemplate.objects.using(db_alias).filter(path=path)
    return (
        templates.filter(managed__isnull=True).first()
        or templates.filter(managed__isnull=False).first()
    )


def backfill_notificationtransport_email_template(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    for transport in NotificationTransport.objects.using(db_alias).all():
        if not transport.email_template_legacy:
            continue
        transport.email_template = resolve_template(
            EmailTemplate, db_alias, transport.email_template_legacy
        )
        transport.save(using=db_alias, update_fields=["email_template"])


def backfill_notificationtransport_email_template_reverse(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    db_alias = schema_editor.connection.alias
    for transport in (
        NotificationTransport.objects.using(db_alias).select_related("email_template").all()
    ):
        transport.email_template_legacy = (
            transport.email_template.path if transport.email_template_id else ""
        )
        transport.save(using=db_alias, update_fields=["email_template_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_events", "0020_alter_event_action"),
        ("authentik_stages_email", "0007_emailtemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationtransport",
            old_name="email_template",
            new_name="email_template_legacy",
        ),
        migrations.AddField(
            model_name="notificationtransport",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentik_stages_email.emailtemplate",
            ),
        ),
        migrations.RunPython(
            backfill_notificationtransport_email_template,
            backfill_notificationtransport_email_template_reverse,
        ),
        migrations.RemoveField(
            model_name="notificationtransport",
            name="email_template_legacy",
        ),
    ]
