# Generated by Django 5.2.17 on 2026-09-14 19:35

from pathlib import Path

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from authentik.lib.config import CONFIG

BUILTIN_PATHS = {
    "email/password_reset.html": "goauthentik.io/email/password-reset",
    "email/account_confirmation.html": "goauthentik.io/email/account-confirmation",
    "email/email_otp.html": "goauthentik.io/email/email-otp",
    "email/event_notification.html": "goauthentik.io/email/event-notification",
    "email/invitation.html": "goauthentik.io/email/invitation",
    "email/setup.html": "goauthentik.io/email/setup",
}


def backfill_notificationtransport_email_template(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    template_dir = Path(CONFIG.get("email.template_dir"))
    for transport in NotificationTransport.objects.using(db_alias).all():
        value = transport.email_template_legacy
        if not value:
            continue
        managed_id = BUILTIN_PATHS.get(value)
        if managed_id:
            transport.email_template = EmailTemplate.objects.using(db_alias).get(managed=managed_id)
            transport.save(using=db_alias, update_fields=["email_template"])
            continue

        try:
            body = (template_dir / value).read_text(encoding="utf-8")
        except OSError:
            continue
        template, _ = EmailTemplate.objects.using(db_alias).get_or_create(
            name=value,
            defaults={"body": body},
        )
        transport.email_template = template
        transport.save(using=db_alias, update_fields=["email_template"])


def backfill_notificationtransport_email_template_reverse(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    NotificationTransport = apps.get_model("authentik_events", "NotificationTransport")
    db_alias = schema_editor.connection.alias
    managed_to_path = {v: k for k, v in BUILTIN_PATHS.items()}
    for transport in (
        NotificationTransport.objects.using(db_alias).select_related("email_template").all()
    ):
        if not transport.email_template_id:
            transport.email_template_legacy = ""
        elif managed_id := transport.email_template.managed:
            transport.email_template_legacy = managed_to_path.get(managed_id, "")
        else:
            transport.email_template_legacy = transport.email_template.name
        transport.save(using=db_alias, update_fields=["email_template_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_events", "0020_alter_event_action"),
        ("authentik_stages_email", "0007_emailtemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationtransport",
            old_name="email_template",
            new_name="email_template_legacy",
        ),
        migrations.AddField(
            model_name="notificationtransport",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentik_stages_email.emailtemplate",
            ),
        ),
        migrations.RunPython(
            backfill_notificationtransport_email_template,
            backfill_notificationtransport_email_template_reverse,
        ),
        migrations.RemoveField(
            model_name="notificationtransport",
            name="email_template_legacy",
        ),
    ]
