# Generated by Django 5.2.17 on 2026-08-10 11:49

import authentik.stages.authenticator_validate.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_stages_authenticator_validate",
            "0017_authenticatorvalidatestageconfigurationstage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticatorvalidatestage",
            name="telegram_otp_throttling_factor",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="authenticatorvalidatestage",
            name="device_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("static", "Static"),
                        ("totp", "TOTP"),
                        ("webauthn", "WebAuthn"),
                        ("duo", "Duo"),
                        ("sms", "SMS"),
                        ("email", "Email"),
                        ("telegram", "Telegram"),
                    ]
                ),
                default=authentik.stages.authenticator_validate.models.default_device_classes,
                help_text="Device classes which can be used to authenticate",
                size=None,
            ),
        ),
    ]
