/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ContextualFlowInfo } from "./ContextualFlowInfo";
import { ContextualFlowInfoFromJSON, ContextualFlowInfoToJSON } from "./ContextualFlowInfo";
import type { ErrorDetail } from "./ErrorDetail";

/**
 * Telegram Setup challenge
 * @export
 * @interface AuthenticatorTelegramChallenge
 */
export interface AuthenticatorTelegramChallenge {
    /**
     *
     * @type {ContextualFlowInfo}
     * @memberof AuthenticatorTelegramChallenge
     */
    flowInfo?: ContextualFlowInfo;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallenge
     */
    component?: string;
    /**
     *
     * @type {{ [key: string]: Array<ErrorDetail>; }}
     * @memberof AuthenticatorTelegramChallenge
     */
    responseErrors?: { [key: string]: Array<ErrorDetail> };
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallenge
     */
    pendingUser: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallenge
     */
    pendingUserAvatar: string;
    /**
     *
     * @type {boolean}
     * @memberof AuthenticatorTelegramChallenge
     */
    codeRequired?: boolean;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallenge
     */
    botUsername: string;
}

/**
 * Check if a given object implements the AuthenticatorTelegramChallenge interface.
 */
export function instanceOfAuthenticatorTelegramChallenge(
    value: object,
): value is AuthenticatorTelegramChallenge {
    if (
        (!("pendingUser" in (value as Record<string, any>)) &&
            !("pending_user" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pendingUser"] === undefined &&
            (value as Record<string, any>)["pending_user"] === undefined)
    )
        return false;
    if (
        (!("pendingUserAvatar" in (value as Record<string, any>)) &&
            !("pending_user_avatar" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["pendingUserAvatar"] === undefined &&
            (value as Record<string, any>)["pending_user_avatar"] === undefined)
    )
        return false;
    if (
        (!("botUsername" in (value as Record<string, any>)) &&
            !("bot_username" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["botUsername"] === undefined &&
            (value as Record<string, any>)["bot_username"] === undefined)
    )
        return false;
    return true;
}

export function AuthenticatorTelegramChallengeFromJSON(json: any): AuthenticatorTelegramChallenge {
    return AuthenticatorTelegramChallengeFromJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthenticatorTelegramChallenge {
    if (json == null) {
        return json;
    }
    return {
        flowInfo:
            json["flow_info"] == null ? undefined : ContextualFlowInfoFromJSON(json["flow_info"]),
        component: json["component"] == null ? undefined : json["component"],
        responseErrors: json["response_errors"] == null ? undefined : json["response_errors"],
        pendingUser: json["pending_user"],
        pendingUserAvatar: json["pending_user_avatar"],
        codeRequired: json["code_required"] == null ? undefined : json["code_required"],
        botUsername: json["bot_username"],
    };
}

export function AuthenticatorTelegramChallengeToJSON(json: any): AuthenticatorTelegramChallenge {
    return AuthenticatorTelegramChallengeToJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeToJSONTyped(
    value?: AuthenticatorTelegramChallenge | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        flow_info: ContextualFlowInfoToJSON(value["flowInfo"]),
        component: value["component"],
        response_errors: value["responseErrors"],
        pending_user: value["pendingUser"],
        pending_user_avatar: value["pendingUserAvatar"],
        code_required: value["codeRequired"],
        bot_username: value["botUsername"],
    };
}
