/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AuthenticatorTelegramStage Serializer
 * @export
 * @interface AuthenticatorTelegramStageRequest
 */
export interface AuthenticatorTelegramStageRequest {
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    name: string;
    /**
     * Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    configureFlow?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    friendlyName?: string;
    /**
     * Telegram bot username
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    botUsername: string;
    /**
     * Telegram bot token
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    botToken: string;
    /**
     * Optionally modify the payload being sent to Telegram.
     * @type {string}
     * @memberof AuthenticatorTelegramStageRequest
     */
    mapping?: string | null;
}

/**
 * Check if a given object implements the AuthenticatorTelegramStageRequest interface.
 */
export function instanceOfAuthenticatorTelegramStageRequest(
    value: object,
): value is AuthenticatorTelegramStageRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (
        (!("botUsername" in (value as Record<string, any>)) &&
            !("bot_username" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["botUsername"] === undefined &&
            (value as Record<string, any>)["bot_username"] === undefined)
    )
        return false;
    if (
        (!("botToken" in (value as Record<string, any>)) &&
            !("bot_token" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["botToken"] === undefined &&
            (value as Record<string, any>)["bot_token"] === undefined)
    )
        return false;
    return true;
}

export function AuthenticatorTelegramStageRequestFromJSON(
    json: any,
): AuthenticatorTelegramStageRequest {
    return AuthenticatorTelegramStageRequestFromJSONTyped(json, false);
}

export function AuthenticatorTelegramStageRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthenticatorTelegramStageRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        configureFlow:
            json["configure_flow"] === undefined
                ? undefined
                : json["configure_flow"] === null
                  ? null
                  : json["configure_flow"],
        friendlyName: json["friendly_name"] == null ? undefined : json["friendly_name"],
        botUsername: json["bot_username"],
        botToken: json["bot_token"],
        mapping:
            json["mapping"] === undefined
                ? undefined
                : json["mapping"] === null
                  ? null
                  : json["mapping"],
    };
}

export function AuthenticatorTelegramStageRequestToJSON(
    json: any,
): AuthenticatorTelegramStageRequest {
    return AuthenticatorTelegramStageRequestToJSONTyped(json, false);
}

export function AuthenticatorTelegramStageRequestToJSONTyped(
    value?: AuthenticatorTelegramStageRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        configure_flow: value["configureFlow"],
        friendly_name: value["friendlyName"],
        bot_username: value["botUsername"],
        bot_token: value["botToken"],
        mapping: value["mapping"],
    };
}
