/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Telegram Challenge response, device is set by get_response_instance
 * @export
 * @interface AuthenticatorTelegramChallengeResponseRequest
 */
export interface AuthenticatorTelegramChallengeResponseRequest {
    /**
     *
     * @type {number}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    photoUrl?: string;
    /**
     *
     * @type {number}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    authDate: number;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    hash: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    component?: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the AuthenticatorTelegramChallengeResponseRequest interface.
 */
export function instanceOfAuthenticatorTelegramChallengeResponseRequest(
    value: object,
): value is AuthenticatorTelegramChallengeResponseRequest {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (
        (!("authDate" in (value as Record<string, any>)) &&
            !("auth_date" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["authDate"] === undefined &&
            (value as Record<string, any>)["auth_date"] === undefined)
    )
        return false;
    if (!("hash" in value) || value["hash"] === undefined) return false;
    return true;
}

export function AuthenticatorTelegramChallengeResponseRequestFromJSON(
    json: any,
): AuthenticatorTelegramChallengeResponseRequest {
    return AuthenticatorTelegramChallengeResponseRequestFromJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeResponseRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthenticatorTelegramChallengeResponseRequest {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        firstName: json["first_name"] == null ? undefined : json["first_name"],
        lastName: json["last_name"] == null ? undefined : json["last_name"],
        username: json["username"] == null ? undefined : json["username"],
        photoUrl: json["photo_url"] == null ? undefined : json["photo_url"],
        authDate: json["auth_date"],
        hash: json["hash"],
        component: json["component"] == null ? undefined : json["component"],
        code: json["code"] == null ? undefined : json["code"],
    };
}

export function AuthenticatorTelegramChallengeResponseRequestToJSON(
    json: any,
): AuthenticatorTelegramChallengeResponseRequest {
    return AuthenticatorTelegramChallengeResponseRequestToJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeResponseRequestToJSONTyped(
    value?: AuthenticatorTelegramChallengeResponseRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        first_name: value["firstName"],
        last_name: value["lastName"],
        username: value["username"],
        photo_url: value["photoUrl"],
        auth_date: value["authDate"],
        hash: value["hash"],
        component: value["component"],
        code: value["code"],
    };
}
