/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Telegram Challenge response, device is set by get_response_instance
 * @export
 * @interface AuthenticatorTelegramChallengeResponseRequest
 */
export interface AuthenticatorTelegramChallengeResponseRequest {
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    component?: string;
    /**
     *
     * @type {string}
     * @memberof AuthenticatorTelegramChallengeResponseRequest
     */
    code?: string;
}

/**
 * Check if a given object implements the AuthenticatorTelegramChallengeResponseRequest interface.
 */
export function instanceOfAuthenticatorTelegramChallengeResponseRequest(
    value: object,
): value is AuthenticatorTelegramChallengeResponseRequest {
    return true;
}

export function AuthenticatorTelegramChallengeResponseRequestFromJSON(
    json: any,
): AuthenticatorTelegramChallengeResponseRequest {
    return AuthenticatorTelegramChallengeResponseRequestFromJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeResponseRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthenticatorTelegramChallengeResponseRequest {
    if (json == null) {
        return json;
    }
    return {
        component: json["component"] == null ? undefined : json["component"],
        code: json["code"] == null ? undefined : json["code"],
    };
}

export function AuthenticatorTelegramChallengeResponseRequestToJSON(
    json: any,
): AuthenticatorTelegramChallengeResponseRequest {
    return AuthenticatorTelegramChallengeResponseRequestToJSONTyped(json, false);
}

export function AuthenticatorTelegramChallengeResponseRequestToJSONTyped(
    value?: AuthenticatorTelegramChallengeResponseRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        component: value["component"],
        code: value["code"],
    };
}
