/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthenticatorTelegramStage } from "./AuthenticatorTelegramStage";
import {
    AuthenticatorTelegramStageFromJSON,
    AuthenticatorTelegramStageToJSON,
} from "./AuthenticatorTelegramStage";
import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";

/**
 *
 * @export
 * @interface PaginatedAuthenticatorTelegramStageList
 */
export interface PaginatedAuthenticatorTelegramStageList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedAuthenticatorTelegramStageList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<AuthenticatorTelegramStage>}
     * @memberof PaginatedAuthenticatorTelegramStageList
     */
    results: Array<AuthenticatorTelegramStage>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedAuthenticatorTelegramStageList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedAuthenticatorTelegramStageList interface.
 */
export function instanceOfPaginatedAuthenticatorTelegramStageList(
    value: object,
): value is PaginatedAuthenticatorTelegramStageList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedAuthenticatorTelegramStageListFromJSON(
    json: any,
): PaginatedAuthenticatorTelegramStageList {
    return PaginatedAuthenticatorTelegramStageListFromJSONTyped(json, false);
}

export function PaginatedAuthenticatorTelegramStageListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedAuthenticatorTelegramStageList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(AuthenticatorTelegramStageFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedAuthenticatorTelegramStageListToJSON(
    json: any,
): PaginatedAuthenticatorTelegramStageList {
    return PaginatedAuthenticatorTelegramStageListToJSONTyped(json, false);
}

export function PaginatedAuthenticatorTelegramStageListToJSONTyped(
    value?: PaginatedAuthenticatorTelegramStageList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(AuthenticatorTelegramStageToJSON),
        autocomplete: value["autocomplete"],
    };
}
