/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from "./Pagination";
import { PaginationFromJSON, PaginationToJSON } from "./Pagination";
import type { TelegramDevice } from "./TelegramDevice";
import { TelegramDeviceFromJSON, TelegramDeviceToJSON } from "./TelegramDevice";

/**
 *
 * @export
 * @interface PaginatedTelegramDeviceList
 */
export interface PaginatedTelegramDeviceList {
    /**
     *
     * @type {Pagination}
     * @memberof PaginatedTelegramDeviceList
     */
    pagination: Pagination;
    /**
     *
     * @type {Array<TelegramDevice>}
     * @memberof PaginatedTelegramDeviceList
     */
    results: Array<TelegramDevice>;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PaginatedTelegramDeviceList
     */
    autocomplete: { [key: string]: any };
}

/**
 * Check if a given object implements the PaginatedTelegramDeviceList interface.
 */
export function instanceOfPaginatedTelegramDeviceList(
    value: object,
): value is PaginatedTelegramDeviceList {
    if (!("pagination" in value) || value["pagination"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    if (!("autocomplete" in value) || value["autocomplete"] === undefined) return false;
    return true;
}

export function PaginatedTelegramDeviceListFromJSON(json: any): PaginatedTelegramDeviceList {
    return PaginatedTelegramDeviceListFromJSONTyped(json, false);
}

export function PaginatedTelegramDeviceListFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PaginatedTelegramDeviceList {
    if (json == null) {
        return json;
    }
    return {
        pagination: PaginationFromJSON(json["pagination"]),
        results: (json["results"] as Array<any>).map(TelegramDeviceFromJSON),
        autocomplete: json["autocomplete"],
    };
}

export function PaginatedTelegramDeviceListToJSON(json: any): PaginatedTelegramDeviceList {
    return PaginatedTelegramDeviceListToJSONTyped(json, false);
}

export function PaginatedTelegramDeviceListToJSONTyped(
    value?: PaginatedTelegramDeviceList | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        pagination: PaginationToJSON(value["pagination"]),
        results: (value["results"] as Array<any>).map(TelegramDeviceToJSON),
        autocomplete: value["autocomplete"],
    };
}
