/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AuthenticatorTelegramStage Serializer
 * @export
 * @interface PatchedAuthenticatorTelegramStageRequest
 */
export interface PatchedAuthenticatorTelegramStageRequest {
    /**
     *
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    name?: string;
    /**
     * Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    configureFlow?: string | null;
    /**
     *
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    friendlyName?: string;
    /**
     * Telegram bot username
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    botUsername?: string;
    /**
     * Telegram bot token
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    botToken?: string;
    /**
     * Optionally modify the payload being sent to Telegram.
     * @type {string}
     * @memberof PatchedAuthenticatorTelegramStageRequest
     */
    mapping?: string | null;
}

/**
 * Check if a given object implements the PatchedAuthenticatorTelegramStageRequest interface.
 */
export function instanceOfPatchedAuthenticatorTelegramStageRequest(
    value: object,
): value is PatchedAuthenticatorTelegramStageRequest {
    return true;
}

export function PatchedAuthenticatorTelegramStageRequestFromJSON(
    json: any,
): PatchedAuthenticatorTelegramStageRequest {
    return PatchedAuthenticatorTelegramStageRequestFromJSONTyped(json, false);
}

export function PatchedAuthenticatorTelegramStageRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedAuthenticatorTelegramStageRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        configureFlow:
            json["configure_flow"] === undefined
                ? undefined
                : json["configure_flow"] === null
                  ? null
                  : json["configure_flow"],
        friendlyName: json["friendly_name"] == null ? undefined : json["friendly_name"],
        botUsername: json["bot_username"] == null ? undefined : json["bot_username"],
        botToken: json["bot_token"] == null ? undefined : json["bot_token"],
        mapping:
            json["mapping"] === undefined
                ? undefined
                : json["mapping"] === null
                  ? null
                  : json["mapping"],
    };
}

export function PatchedAuthenticatorTelegramStageRequestToJSON(
    json: any,
): PatchedAuthenticatorTelegramStageRequest {
    return PatchedAuthenticatorTelegramStageRequestToJSONTyped(json, false);
}

export function PatchedAuthenticatorTelegramStageRequestToJSONTyped(
    value?: PatchedAuthenticatorTelegramStageRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        configure_flow: value["configureFlow"],
        friendly_name: value["friendlyName"],
        bot_username: value["botUsername"],
        bot_token: value["botToken"],
        mapping: value["mapping"],
    };
}
