/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Serializer for Telegram authenticator devices
 * @export
 * @interface PatchedTelegramDeviceRequest
 */
export interface PatchedTelegramDeviceRequest {
    /**
     * The human-readable name of this device.
     * @type {string}
     * @memberof PatchedTelegramDeviceRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the PatchedTelegramDeviceRequest interface.
 */
export function instanceOfPatchedTelegramDeviceRequest(
    value: object,
): value is PatchedTelegramDeviceRequest {
    return true;
}

export function PatchedTelegramDeviceRequestFromJSON(json: any): PatchedTelegramDeviceRequest {
    return PatchedTelegramDeviceRequestFromJSONTyped(json, false);
}

export function PatchedTelegramDeviceRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedTelegramDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function PatchedTelegramDeviceRequestToJSON(json: any): PatchedTelegramDeviceRequest {
    return PatchedTelegramDeviceRequestToJSONTyped(json, false);
}

export function PatchedTelegramDeviceRequestToJSONTyped(
    value?: PatchedTelegramDeviceRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
