/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PartialUser } from "./PartialUser";
import { PartialUserFromJSON } from "./PartialUser";

/**
 * Serializer for Telegram authenticator devices
 * @export
 * @interface TelegramDevice
 */
export interface TelegramDevice {
    /**
     * The human-readable name of this device.
     * @type {string}
     * @memberof TelegramDevice
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof TelegramDevice
     */
    readonly pk: number;
    /**
     *
     * @type {PartialUser}
     * @memberof TelegramDevice
     */
    readonly user: PartialUser;
    /**
     *
     * @type {string}
     * @memberof TelegramDevice
     */
    readonly chatId: string;
}

/**
 * Check if a given object implements the TelegramDevice interface.
 */
export function instanceOfTelegramDevice(value: object): value is TelegramDevice {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("user" in value) || value["user"] === undefined) return false;
    if (
        (!("chatId" in (value as Record<string, any>)) &&
            !("chat_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["chatId"] === undefined &&
            (value as Record<string, any>)["chat_id"] === undefined)
    )
        return false;
    return true;
}

export function TelegramDeviceFromJSON(json: any): TelegramDevice {
    return TelegramDeviceFromJSONTyped(json, false);
}

export function TelegramDeviceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TelegramDevice {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
        pk: json["pk"],
        user: PartialUserFromJSON(json["user"]),
        chatId: json["chat_id"],
    };
}

export function TelegramDeviceToJSON(json: any): TelegramDevice {
    return TelegramDeviceToJSONTyped(json, false);
}

export function TelegramDeviceToJSONTyped(
    value?: Omit<TelegramDevice, "pk" | "user" | "chatId"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
