/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Serializer for Telegram authenticator devices
 * @export
 * @interface TelegramDeviceRequest
 */
export interface TelegramDeviceRequest {
    /**
     * The human-readable name of this device.
     * @type {string}
     * @memberof TelegramDeviceRequest
     */
    name: string;
}

/**
 * Check if a given object implements the TelegramDeviceRequest interface.
 */
export function instanceOfTelegramDeviceRequest(value: object): value is TelegramDeviceRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function TelegramDeviceRequestFromJSON(json: any): TelegramDeviceRequest {
    return TelegramDeviceRequestFromJSONTyped(json, false);
}

export function TelegramDeviceRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TelegramDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"],
    };
}

export function TelegramDeviceRequestToJSON(json: any): TelegramDeviceRequest {
    return TelegramDeviceRequestToJSONTyped(json, false);
}

export function TelegramDeviceRequestToJSONTyped(
    value?: TelegramDeviceRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
    };
}
