# Generated by Django 5.2.17 on 2026-09-14 19:35

from pathlib import Path

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from authentik.lib.config import CONFIG

BUILTIN_PATHS = {
    "email/password_reset.html": "goauthentik.io/email/password-reset",
    "email/account_confirmation.html": "goauthentik.io/email/account-confirmation",
    "email/email_otp.html": "goauthentik.io/email/email-otp",
    "email/event_notification.html": "goauthentik.io/email/event-notification",
    "email/invitation.html": "goauthentik.io/email/invitation",
    "email/setup.html": "goauthentik.io/email/setup",
}


def backfill_authenticatoremailstage_template(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    AuthenticatorEmailStage = apps.get_model(
        "authentik_stages_authenticator_email", "AuthenticatorEmailStage"
    )
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    template_dir = Path(CONFIG.get("email.template_dir"))
    for stage in AuthenticatorEmailStage.objects.using(db_alias).all():
        value = stage.template_legacy
        if not value:
            continue
        managed_id = BUILTIN_PATHS.get(value)
        if managed_id:
            stage.template = EmailTemplate.objects.using(db_alias).get(managed=managed_id)
            stage.save(using=db_alias, update_fields=["template"])
            continue

        try:
            body = (template_dir / value).read_text(encoding="utf-8")
        except OSError:
            continue
        template, _ = EmailTemplate.objects.using(db_alias).get_or_create(
            name=value,
            defaults={"body": body},
        )
        stage.template = template
        stage.save(using=db_alias, update_fields=["template"])


def backfill_authenticatoremailstage_template_reverse(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    AuthenticatorEmailStage = apps.get_model(
        "authentik_stages_authenticator_email", "AuthenticatorEmailStage"
    )
    db_alias = schema_editor.connection.alias
    managed_to_path = {v: k for k, v in BUILTIN_PATHS.items()}
    for stage in AuthenticatorEmailStage.objects.using(db_alias).select_related("template").all():
        if not stage.template_id:
            stage.template_legacy = ""
        elif managed_id := stage.template.managed:
            stage.template_legacy = managed_to_path.get(managed_id, "")
        else:
            stage.template_legacy = stage.template.name
        stage.save(using=db_alias, update_fields=["template_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_authenticator_email", "0004_alter_emaildevice_stage"),
        ("authentik_stages_email", "0007_emailtemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authenticatoremailstage",
            old_name="template",
            new_name="template_legacy",
        ),
        migrations.AddField(
            model_name="authenticatoremailstage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentik_stages_email.emailtemplate",
            ),
        ),
        migrations.RunPython(
            backfill_authenticatoremailstage_template,
            backfill_authenticatoremailstage_template_reverse,
        ),
        migrations.RemoveField(
            model_name="authenticatoremailstage",
            name="template_legacy",
        ),
    ]
