# Generated by Django 5.2.17 on 2026-09-14 19:35

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def resolve_template(EmailTemplate, db_alias: str, path: str):
    templates = EmailTemplate.objects.using(db_alias).filter(path=path)
    return (
        templates.filter(managed__isnull=True).first()
        or templates.filter(managed__isnull=False).first()
    )


def backfill_authenticatoremailstage_template(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    AuthenticatorEmailStage = apps.get_model(
        "authentik_stages_authenticator_email", "AuthenticatorEmailStage"
    )
    EmailTemplate = apps.get_model("authentik_stages_email", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    for stage in AuthenticatorEmailStage.objects.using(db_alias).all():
        if not stage.template_legacy:
            continue
        stage.template = resolve_template(EmailTemplate, db_alias, stage.template_legacy)
        stage.save(using=db_alias, update_fields=["template"])


def backfill_authenticatoremailstage_template_reverse(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
):
    AuthenticatorEmailStage = apps.get_model(
        "authentik_stages_authenticator_email", "AuthenticatorEmailStage"
    )
    db_alias = schema_editor.connection.alias
    for stage in AuthenticatorEmailStage.objects.using(db_alias).select_related("template").all():
        stage.template_legacy = stage.template.path if stage.template_id else ""
        stage.save(using=db_alias, update_fields=["template_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_stages_authenticator_email", "0004_alter_emaildevice_stage"),
        ("authentik_stages_email", "0007_emailtemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authenticatoremailstage",
            old_name="template",
            new_name="template_legacy",
        ),
        migrations.AddField(
            model_name="authenticatoremailstage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentik_stages_email.emailtemplate",
            ),
        ),
        migrations.RunPython(
            backfill_authenticatoremailstage_template,
            backfill_authenticatoremailstage_template_reverse,
        ),
        migrations.RemoveField(
            model_name="authenticatoremailstage",
            name="template_legacy",
        ),
    ]
